# Generated by Django 4.0 on 2022-05-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_remove_register_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
