# Generated by Django 4.0 on 2022-05-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_remove_register_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='People',
        ),
    ]
